# For more information: https://laravel.com/docs/sail
services:
  app:
    build:
      context: ./
      dockerfile: ./deploy/Dockerfile
    container_name: app_device_management
    volumes:
      - '.:/var/www/html/device_management'
    env_file: ./.env
    networks:
      - sail
    depends_on:
      - db
  db:
    image: 'mysql:latest'
    container_name: db_device_management
    privileged: true
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'device_management'
      MYSQL_USER: 'user_01'
      MYSQL_PASSWORD: '12345678'
    volumes:
      - ./db-data:/var/lib/mysql
      - ./deploy/mysqld.cnf:/etc/mysql/conf.d/my-resolve.cnf:ro
    networks:
      - sail
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_device_management
    restart: unless-stopped
    ports:
      - '${PHPMYADMIN_PORT}:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
      UPLOAD_LIMIT: 3000M
    networks:
      - sail
  nginx:
    image: nginx:1.23.0-alpine
    container_name: nginx_device_management
    privileged: true
    ports:
      - '${NGINX_PORT}:80'
    volumes:
      - '/usr/share/nginx/html/swagger-ui'
      - './deploy/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html/device_management'
    networks:
      - sail
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: swagger_editor_device_management
    volumes:
      - ./deploy/api-docs:/usr/share/nginx/html/api-docs  
    environment:
        SWAGGER_FILE: /usr/share/nginx/html/api-docs/openapi.yaml 
    ports:
      - "${SWAGGER_EDITOR_PORT:-5050}:8080"
    networks:
      - sail
    depends_on:
      - app

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_device_management
    ports:
      - "${SWAGGER_UI_PORT:-5051}:8080"
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/api-docs/openapi.yaml
    volumes:
    - ./deploy/api-docs:/usr/share/nginx/html/api-docs
    networks:
      - sail
    depends_on:
      - app

networks:
  sail:
    driver: bridge

volumes:
  db-data:
    driver: local
