services:
    app:
        build:
            context: ./
            dockerfile: ./deploy/Dockerfile
        container_name: app_httm
        volumes:
            - ".:/var/www/html/httm"
        env_file: ./.env
        networks:
            - sail
        depends_on:
            - db

    db:
        image: "mysql:latest"
        container_name: db_httm
        privileged: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "httm"
            MYSQL_USER: "user_01"
            MYSQL_PASSWORD: "12345678"
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - sail

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_httm
        restart: unless-stopped
        ports:
            - "8080:10000"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - sail

    nginx:
        image: nginx:1.23.0-alpine
        container_name: nginx_httm
        ports:
            - "${PORT}:10000"  # Map host port 8001 → container port 80
        volumes:
            - "./deploy/nginx.conf:/etc/nginx/conf.d/default.conf"
            - ".:/var/www/html/httm"
        networks:
            - sail
        depends_on:
            - app

networks:
    sail:
        driver: bridge

volumes:
    db-data:
        driver: local