openapi: 3.0.0
info:
  title: Swap
  description: API for managing swap resources
  version: 1.0.0

servers:
  - url: http://localhost:8001
  - url: http://dev.device-management.cssoft.jp

paths:
  /api/login:
    post:
      tags:
        - User Authentication
      summary: User login
      description: Authenticate a user and return an access token.
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseLogin"

  /api/logout:
    get:
      tags:
        - User Authentication
      summary: User logout
      description: Logout a user and invalidate the access token.
      operationId: logout
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful logout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseLogout"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseLogout"
  /api/v1/devices:
    post:
      tags:
        - Device Management
      summary: Create a new device
      description: Add a new device to the system.
      operationId: createDevice
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: Device Name
                code:
                  type: string
                  maxLength: 255
                  example: DEV-001
                device_type_id:
                  type: integer
                  example: 1
                custom_device_type:
                  type: string
                  nullable: true
                  example: Custom Type
                  description: Required if `device_type_id` is -1
                quantity:
                  type: integer
                  minimum: 1
                  example: 10
                unit:
                  type: string
                  maxLength: 50
                  example: pcs
                status:
                  type: string
                  maxLength: 50
                  example: Active
                location:
                  type: string
                  maxLength: 255
                  example: Warehouse A
                image:
                  type: string
                  format: binary
                  description: Image file (jpeg, png, jpg, gif) with a maximum size of 5MB
                specifications:
                  type: string
                  maxLength: 255
                  nullable: true
                  example: "Power: 600W, Speed: 2800 RPM"
                notes:
                  type: string
                  maxLength: 255
                  nullable: true
                  example: "This is a test note."
              required:
                - name
                - code
                - device_type_id
                - quantity
                - unit
                - status
                - location
                - image
      responses:
        "200":
          description: Device created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Thêm thiết bị thành công
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      error:
                        type: string
                        example: Thiết bị đã tồn tại
                  - type: object
                    properties:
                      errors:
                        type: object
                        properties:
                          name:
                            type: array
                            items:
                              type: string
                            example: ["Tên thiết bị là bắt buộc."]
                          code:
                            type: array
                            items:
                              type: string
                            example: ["Mã thiết bị đã tồn tại."]
  /api/v1/devices/{id}:
    get:
      tags:
        - Device Management
      summary: Get device details
      description: Retrieve details of a specific device by its ID.
      operationId: getDevice
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the device to retrieve
          schema:
            type: integer
      responses:
        "200":
          description: Device details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  name:
                    type: string
                    example: "Device Name"
                  code:
                    type: string
                    example: "DEV-001"
                  device_type:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: "Device Type"
                      created_at:
                        type: string
                        format: date-time
                        example: "2025-05-06T11:52:38.000000Z"
                      updated_at:
                        type: string
                        format: date-time
                        example: "2025-05-06T11:52:38.000000Z"
                  device_type_id:
                    type: integer
                    example: 1
                  quantity:
                    type: integer
                    example: 1
                  unit:
                    type: string
                    example: "gấ"
                  location:
                    type: string
                    example: "Kho A"
                  status:
                    type: string
                    example: "old"
                  image_url:
                    type: string
                    format: uri
                    example: "/storage/attachments/7g6/xlx/ajl/7g6xlxajlss55mzgbp6142ces.png"
                  specifications:
                    type: string
                    example: "Power: 600W, Speed: 2800 RPM"
                  notes:
                    type: string
                    example: "This is a test note."
                  created_at:
                    type: string
                    format: date-time
                    example: "2025-05-07T04:05:26.000000Z"
                  updated_at:
                    type: string
                    format: date-time
                    example: "2025-05-07T04:05:26.000000Z"
                  deleted_at:
                    type: string
                    format: date-time
                    nullable: true
                    example: null
                  logs:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 14
                        device_id:
                          type: integer
                          example: 11
                        user_id:
                          type: integer
                          example: 1
                        action:
                          type: string
                          example: "created"
                        changes:
                          type: string
                          nullable: true
                          example: null
                        created_at:
                          type: string
                          format: date-time
                          example: "2025-05-07T04:05:26.000000Z"
        "404":
          description: Device not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Thiết bị không tồn tại

    put:
      tags:
        - Device Management
      summary: Edit device details
      description: Update details of a specific device by its ID.
      operationId: editDevice
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the device to edit
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 255
                  example: "Device Name"
                code:
                  type: string
                  maxLength: 255
                  example: "DEV-001"
                device_type_id:
                  type: integer
                  example: 1
                custom_device_type:
                  type: string
                  nullable: true
                  maxLength: 255
                  example: "Custom Type"
                  description: Required if `device_type_id` is -1
                quantity:
                  type: integer
                  minimum: 0
                  example: 10
                unit:
                  type: string
                  maxLength: 50
                  example: "pcs"
                status:
                  type: string
                  maxLength: 50
                  example: "Active"
                location:
                  type: string
                  maxLength: 255
                  example: "Warehouse A"
                image:
                  type: string
                  format: binary
                  description: Image file (jpeg, png, jpg, gif) with a maximum size of 5MB
                specifications:
                  type: string
                  nullable: true
                  example: "Power: 600W, Speed: 2800 RPM"
                notes:
                  type: string
                  nullable: true
                  maxLength: 255
                  example: "This is a test note."
              required:
                - name
                - code
                - device_type_id
                - quantity
                - unit
                - status
                - location
      responses:
        "200":
          description: Device updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cập nhật thiết bị thành công"
        "404":
          description: Device not found for editing
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Thiết bị không tồn tại"
        "422":
          description: Validation error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        items:
                          type: string
                        example: ["Tên thiết bị là bắt buộc."]
                      code:
                        type: array
                        items:
                          type: string
                        example: ["Mã thiết bị đã tồn tại."]
tags:
  - name: User Authentication
    description: Operations related to user authentication

  - name: Device Management
    description: Operations related to device management

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: email
        password:
          type: string
          example: password
      required:
        - email
        - password

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        message:
          type: string
          example: Đăng nhập thành công!
        user:
          type: object
          properties:
            id:
              type: integer
              example: 1
            email:
              type: string
              example: admin1@gmail.com
            name:
              type: string
              example: Test User
            created_at:
              type: string
              format: date-time
              example: 2025-05-06T09:45:53.000000Z
            updated_at:
              type: string
              format: date-time
              example: 2025-05-06T09:45:53.000000Z

    MessageResponse:
      type: object
      properties:
        message:
          type: string
          example: Đăng xuất thành công!

    ErrorResponseLogin:
      type: object
      properties:
        error:
          type: string
          example: Thông tin không đúng, sai email hoặc mật khẩu

    ErrorResponseLogout:
      type: object
      properties:
        error:
          type: string
          example: Đăng xuất thất bại.
